ALTER TABLE products ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN category TEXT NOT NULL DEFAULT '';
